services:
  nacos:
    image: nacos/nacos-server:v2.5.0  # 使用2.5.0 高了有问题
    container_name: nacos-single
    environment:
      - MODE=standalone  # 单机模式
      - PREFER_IPv4_STACK=true
    ports:
      - "8848:8848"     # Nacos 服务端口
      - "9848:9848"     # Nacos 安全端口（可选）
    volumes:
      - ./data:/home/nacos/data  # 持久化数据
      - ./logs:/home/nacos/logs  # 日志目录
    restart: always
    mem_limit: 2g  # 限制容器内存为 2GB